run:
  timeout: 5m
  tests: true
  skip-dirs:
    - test/vpp_poc
    - vendor

linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - goconst
    - gocyclo
    - lll
    - errcheck
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - lll
      source: "^//go:generate "
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
