version: "2"

run:
  timeout: 5m
  tests: true

linters-settings:
  govet:
    enable-all: true
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
  disable:
    - errcheck

issues:
  exclude-dirs:
    - test/vpp_poc
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
